### ISSUE TITLE
When adding a .csv parser to app.js - protected accounts err handling is altered

### ISSUE THREAD

**Issue by innosoljim** [freethejazz/twitter-to-neo4j#3]
<//app.js
var config = require('./config');
var connector = require('./support');

const parse = require('csv-parse');
const fs = require('fs');
const async = require('async');
const inputFile = 'UCMsocialmediaload1.csv';

let isFirstRead = true;
let screenNameIndex = -1;

var parser = parse({delimiter: ','}, function (err, data) {
  async.eachSeries(data, function (line, callback) {
    if (isFirstRead) {
      screenNameIndex = line.indexOf('screen_name');
      isFirstRead = false;
      return callback();
    }
    const screenName = line[18].trim();
    if (!screenName) {
      return callback();
    }

    // Call Api twitter here with Screen Name
connector.getUserFromTwitter(screenName)
  .then(connector.cypherUpsertOne)
  .then(connector.getWebForHandle)

  .then(function() {
    console.log('List completed for ' + screenName);
}, genericErr); {

    setTimeout(callback, 500);  
  });
}

fs.createReadStream(inputFile).pipe(parser);>

**Comment by innosoljim** [comment]
We were having issues with timeouts - as well as protected accounts these issues lead to the following error being stuck in the app.js start up - due to it hold the "protected name in que" thus looping the error.

 //c:\Users\jim.morgan\Documents\Twitter_API_4_neo4j>node app.js
Wed Feb 01 2017 11:57:21 GMT-0600 (Central Standard Time) - getting web for tcamlin
Wed Feb 01 2017 11:57:21 GMT-0600 (Central Standard Time) - Starting HTTP request
Wed Feb 01 2017 11:57:21 GMT-0600 (Central Standard Time) - Starting HTTP request
{ Error: Not authorized.
    at Object.exports.makeTwitError (c:\Users\jim.morgan\Documents\Twitter_API_4_neo4j\node_modules
\twit\lib\helpers.js:74:13)
    at onRequestComplete (c:\Users\jim.morgan\Documents\Twitter_API_4_neo4j\node_modules\twit\lib\t
witter.js:321:25)
    at Request.<anonymous> (c:\Users\jim.morgan\Documents\Twitter_API_4_neo4j\node_modules\twit\lib
\twitter.js:341:7)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at Gunzip.<anonymous> (c:\Users\jim.morgan\Documents\Twitter_API_4_neo4j\node_modules\request\r
equest.js:1001:12)
    at Gunzip.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at Gunzip.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  message: 'Not authorized.',
  code: null,
  allErrors: [ { request: '/1.1/friends/list.json', error: 'Not authorized.' } ],
  twitterReply: { request: '/1.1/friends/list.json', error: 'Not authorized.' },
  statusCode: 401 }//
